spring:
  datasource:
    url: jdbc:postgresql://localhost/spring_data_access_database?serverTimezone=UTC
    username: spring_data_access
    password: SuperPassword1!
    driver-class-name: org.postgresql.Driver
  security:
    oauth2:
      social-login-url: /api/v1/login/provider/
      client:
        registration:
          github:
            clientId: f1560abc130dc44a30ef
            clientSecret: 1d2c76b5281afbaa3fafd3ee0da6c034dce1df82
            scope:
              - user:email
              - read:user
  jpa:
    generate-dll: true
    show-sql: true
  flyway:
    locations: /db/postgresql
    url: jdbc:postgresql://localhost/spring_data_access_database?serverTimezone=UTC
    user: spring_data_access
    password: SuperPassword1!

server:
  port: 9091

logging:
  level:
    root: DEBUG
    org:
      springframework:
        web: DEBUG
        security: DEBUG
        boot:
          autoconfigure: DEBUG

jwt:
  issuer: andriiyan
  secret: andriisecret
